---
# This task deploys with kubectl apply -f <filename>
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-kubectl
spec:
  params:
    - name: path
      description: Path to the manifest to apply
  resources:
    inputs:
      - name: source
        type: storage
  steps:
    - name: run-kubectl
      image: lachlanevenson/k8s-kubectl
      command: ['kubectl']
      args:
        - 'apply'
        - '-f'
        - '$(resources.inputs.source.location)/$(params.path)'
---